# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 18:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='poloniex', max_length=16)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
    ]
