# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex'), (2, 'binance')]),
        ),
    ]
