# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 20:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
            ],
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
