# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_source', models.SmallIntegerField(choices=[(0, 'reddit'), (1, 'bitcointalk'), (2, 'twitter')])),
                ('topic', models.CharField(max_length=6)),
                ('model', models.SmallIntegerField(choices=[(0, 'vader'), (1, 'nn_sentiment')])),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField(null=True)),
                ('compound', models.FloatField(null=True)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('from_comments', models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['timestamp', 'model', 'sentiment_source', 'topic'], name='sentiment_s_timesta_787bb8_idx'),
        ),
    ]
