# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField(null=True)),
                ('group_chat_id', models.IntegerField(null=True)),
                ('user_chat_id', models.IntegerField(null=True)),
                ('username', models.CharField(default='', max_length=32)),
                ('bot_command_text', models.CharField(default='', max_length=64)),
                ('language_code', models.CharField(default='', max_length=8)),
                ('datetime', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
    ]
