# No signals for this coins
BLACKLISTED_COINS = ['ITT', 'BCC', 'TUSD', ]

BINANCE_WHITELIST = """BTC/USDT ETH/USDT TRX/BTC TRX/USDT ETH/BTC XRP/USDT
    WAVES/BTC EOS/USDT XRP/BTC TUSD/BTC BCHSV/USDT DLT/BTC PAX/USDT LINK/BTC
    BNB/USDT BCHABC/USDT BNB/BTC ADA/USDT LTC/USDT BCHSV/BTC BCHABC/BTC
    TUSD/USDT PHX/BTC NEO/USDT XLM/USDT BTC/USDC ADA/BTC XLM/BTC EOS/BTC
    LTC/BTC TRX/ETH NEO/BTC QKC/BTC HC/BTC ONT/USDT ZIL/BTC USDC/USDT TRX/TUSD
    LEND/BTC VIBE/BTC TRX/XRP XMR/BTC ETC/USDT XRP/ETH ICX/BTC ETH/USDC ONT/BTC
    VET/USDT XVG/BTC RVN/BTC WAVES/ETH PAX/BTC PPT/BTC ZEC/BTC ICX/USDT
    IOTA/USDT TUSD/ETH DASH/BTC VET/BTC ETC/BTC XEM/BTC IOTA/BTC ZRX/BTC
    HOT/BTC BNB/ETH XRP/USDC DLT/ETH IOST/BTC ARN/BTC WTC/BTC QTUM/USDT EOS/ETH
    DOCK/BTC WAN/BTC STRAT/BTC NANO/BTC HOT/ETH BAT/BTC QTUM/BTC OMG/BTC
    LUN/BTC LINK/ETH XLM/USDC VIB/BTC POLY/BTC ADA/ETH XLM/ETH AION/BTC
    NPXS/BTC NEO/ETH MANA/BTC INS/BTC MITH/BTC IOTX/BTC MDA/BTC HC/ETH GVT/BTC
    NPXS/ETH MTL/BTC NCASH/BTC ELF/BTC POWR/BTC CMT/BTC OMG/ETH STEEM/BTC
    GO/BTC LTC/ETH ZIL/ETH KNC/BTC SC/BTC IOTA/ETH PHX/ETH GTO/BTC PIVX/BTC
    LSK/BTC LOOM/BTC ENJ/BTC SNT/BTC MFT/BTC REP/BTC KEY/BTC SALT/BTC POA/BTC
    FUEL/BTC EOS/USDC DOCK/ETH STORM/BTC DCR/BTC ARDR/BTC BCPT/BTC MTH/BTC
    MOD/BTC REN/BTC DENT/BTC AE/BTC VET/ETH AGI/BTC GTO/ETH POE/BTC YOYO/BTC
    NXS/BTC PPT/ETH PAX/ETH NAS/BTC QKC/ETH AST/BTC STORJ/BTC REQ/BTC CLOAK/BTC
    SKY/BTC BTG/BTC ONT/ETH ARN/ETH GNT/BTC NULS/BTC BCD/BTC OST/BTC VIBE/ETH
    KNC/ETH QTUM/ETH ADX/BTC THETA/BTC SUB/BTC XVG/ETH DASH/ETH MCO/BTC ZRX/ETH
    ZEN/BTC XMR/ETH XEM/ETH WABI/BTC OAX/BTC ICX/ETH GAS/BTC BLZ/BTC NEBL/BTC
    KMD/BTC FUN/BTC ETC/ETH ENG/BTC AMB/BTC CVC/BTC LEND/ETH CDT/BTC ZEC/ETH
    STRAT/ETH NULS/USDT WINGS/BTC SNM/BTC DNT/BTC RDN/BTC SNT/ETH TNB/BTC
    WPR/BTC XZC/BTC IOST/ETH BTS/BTC ARK/BTC BQX/BTC BAT/ETH NANO/ETH SYS/BTC
    APPC/BTC TNT/BTC DGD/BTC EVX/BTC LRC/BTC MANA/ETH GXS/BTC MDA/ETH VIB/ETH
    EDO/BTC AE/ETH CND/BTC AION/ETH ENJ/ETH INS/ETH RCN/BTC BRD/BTC SNGLS/BTC
    CMT/ETH SC/ETH QLC/BTC BNT/BTC QSP/BTC WTC/ETH NAV/BTC LUN/ETH LOOM/ETH
    WAN/ETH POA/ETH VIA/BTC STEEM/ETH""".split()