# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('UI', models.SmallIntegerField(choices=[(0, 'telegram bot'), (1, 'web app')], default=0)),
                ('subscribers_only', models.BooleanField(default=True)),
                ('text', models.TextField(default='')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')], default=0)),
                ('coin', models.CharField(max_length=6)),
                ('signal', models.CharField(max_length=15, null=True)),
                ('trend', models.CharField(max_length=15, null=True)),
                ('risk', models.SmallIntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], null=True)),
                ('horizon', models.SmallIntegerField(choices=[(0, 'short'), (1, 'medium'), (2, 'long')], null=True)),
                ('strength_value', models.IntegerField(null=True)),
                ('strength_max', models.IntegerField(null=True)),
                ('price_satoshis', models.BigIntegerField()),
                ('price_satoshis_change', models.FloatField(null=True)),
                ('price_usdt', models.FloatField(null=True)),
                ('price_usdt_change', models.FloatField(null=True)),
                ('volume_btc', models.FloatField(null=True)),
                ('volume_btc_change', models.FloatField(null=True)),
                ('volume_usdt', models.FloatField(null=True)),
                ('volume_usdt_change', models.FloatField(null=True)),
                ('sent_at', unixtimestampfield.fields.UnixTimeStampField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
