# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 20:10
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='timestamp',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
