# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 20:03
from __future__ import unicode_literals

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0002_signal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='sent_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=None, null=True),
        ),
    ]
