# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0002_signal_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='rsi_value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
