# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0005_signal_rsi_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='price_satoshis',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='price_satoshis_change',
            new_name='price_change',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='price_usdt',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='price_usdt_change',
        ),
        migrations.AddField(
            model_name='signal',
            name='base_coin',
            field=models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0),
        ),


    ]
