# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0008_signal_resample_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
