# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0008_signal_resample_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='predicted_ahead_for',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='probability_down',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='probability_same',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='probability_up',
            field=models.FloatField(null=True),
        ),
    ]
