# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0010_add_more_sources'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['source', 'resample_period', 'counter_currency', 'transaction_currency'], name='signal_sign_source_da8a8b_idx'),
        ),
    ]
