# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171018_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horizon',
            field=models.SmallIntegerField(choices=[(0, 'short'), (1, 'medium'), (2, 'long')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='risk',
            field=models.SmallIntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], default=0),
        ),
    ]
