# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171019_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='beta_subscription_token',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_since',
            field=models.DateTimeField(null=True),
        ),
    ]
