# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171116_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ITT_team',
            field=models.BooleanField(default=False),
        ),
    ]
