# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('strategy_name', models.CharField(max_length=32)),
                ('backtested_performance', models.FloatField(null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Strategy')),
            ],
        ),
    ]
