# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtest',
            old_name='backtested_performance',
            new_name='backtested_performance_1',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='strategy_name',
        ),
        migrations.AddField(
            model_name='backtest',
            name='backtested_performance_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy_class_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
