# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_auto_20180416_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtest',
            old_name='backtested_performance_1',
            new_name='avg_profit_per_trade_pair',
        ),
        migrations.RenameField(
            model_name='backtest',
            old_name='backtested_performance_2',
            new_name='buy_and_hold_profit_percent',
        ),
        migrations.AddField(
            model_name='backtest',
            name='buy_and_hold_profit_percent_USDT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='counter_currency',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='end_timeframe',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='num_buys',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='num_profitable_trade_pairs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='num_sells',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='num_trades',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='percent_gain_over_buy_and_hold',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='percent_gain_over_buy_and_hold_USDT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='profit_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='profit_percent_USDT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='source',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='start_timeframe',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='status',
            field=models.CharField(default='ok', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='transaction_currency',
            field=models.CharField(default='BTC', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backtest',
            name='strategy_class_name',
            field=models.CharField(default='rsi_simple', max_length=64),
            preserve_default=False,
        ),
    ]
