# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('to_address', models.CharField(max_length=140)),
                ('from_address', models.CharField(default='info@intelligenttrading.org', max_length=140)),
                ('subject', models.TextField(max_length=140)),
                ('body', models.TextField(default='')),
                ('is_html_body', models.BooleanField(default=False)),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'notification'), (1, 'email confirmation')], default=0, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('attachments', models.ManyToManyField(to='common.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
