# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('coin', models.CharField(max_length=6)),
                ('satoshis', models.BigIntegerField()),
                ('wei', models.BigIntegerField(null=True)),
                ('usdt', models.FloatField(null=True)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('coin', models.CharField(max_length=6)),
                ('btc_volume', models.FloatField()),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
            ],
        ),
    ]
