# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceResampled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('coin', models.CharField(max_length=6)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('period', models.PositiveSmallIntegerField(default=15)),
                ('mean_price_satoshis', models.IntegerField(null=True)),
                ('min_price_satoshis', models.IntegerField(null=True)),
                ('max_price_satoshis', models.IntegerField(null=True)),
                ('SMA50_satoshis', models.IntegerField(null=True)),
                ('SMA200_satoshis', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
