# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_priceresampled'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceresampled',
            name='EMA200_satoshis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='EMA50_satoshis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='relative_strength',
            field=models.FloatField(null=True),
        ),
    ]
