# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20171030_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('coin', 'timestamp')]),
        ),
    ]
