# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20171030_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='satoshis',
            new_name='price_satoshis',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='usdt',
            new_name='price_usdt',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='wei',
            new_name='price_wei',
        ),
    ]
