# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


# Schema migration
class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20171104_1440'),
    ]

    operations = [
        # price
        migrations.AddField(
            model_name='price',
            name='base_coin',
            field=models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0),
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_satoshis',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_usdt',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_wei',
        ),


        # price_resampled
        migrations.AddField(
            model_name='priceresampled',
            name='base_coin',
            field=models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='price_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='closing_price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='EMA200_satoshis',
            new_name='ema_high_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='EMA50_satoshis',
            new_name='ema_low_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='SMA200_satoshis',
            new_name='sma_high_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='SMA50_satoshis',
            new_name='sma_low_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='max_price_satoshis',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='mean_price_satoshis',
            new_name='mean_price',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='min_price_satoshis',
            new_name='min_price',
        ),


        migrations.AddField(
            model_name='priceresampled',
            name='ema_high_period',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='ema_low_period',
            field=models.PositiveSmallIntegerField(default=50),
        ),

        migrations.AddField(
            model_name='priceresampled',
            name='sma_high_period',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='priceresampled',
            name='sma_low_period',
            field=models.PositiveSmallIntegerField(default=50),
        ),

        # Price Data migration

    ]
