# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20171108_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('coin', 'timestamp')]),
        ),
    ]
