# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_auto_20171206_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceresampled',
            name='closing_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
