# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20171207_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='btc_volume',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='volume',
            name='base_coin',
            field=models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0),
        ),
    ]
