# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20171207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceresampled',
            name='max_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='mean_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='min_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
