# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20171208_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceresampled',
            name='ema_high_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='ema_low_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='sma_high_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='sma_low_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
