# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_auto_20171208_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='base_coin',
            new_name='counter_currency',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='coin',
            new_name='transaction_currency',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='base_coin',
            new_name='counter_currency',
        ),
        migrations.RenameField(
            model_name='priceresampled',
            old_name='coin',
            new_name='transaction_currency',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='base_coin',
            new_name='counter_currency',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='coin',
            new_name='transaction_currency',
        ),
    ]
