# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '__first__'),
        ('indicator', '0011_auto_20180129_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnPriceClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('counter_currency', models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0)),
                ('transaction_currency', models.CharField(max_length=6)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('resample_period', models.PositiveSmallIntegerField(default=60)),
                ('predicted_ahead_for', models.SmallIntegerField()),
                ('probability_same', models.FloatField(null=True)),
                ('probability_up', models.FloatField(null=True)),
                ('probability_down', models.FloatField(null=True)),
                ('nn_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.AnnModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
