# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20180117_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceresampled',
            name='period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='eventselementary',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='eventslogical',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='priceresampl',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='priceresampled',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='rsi',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='sma',
            name='resample_period',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
