# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_rsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsrsi',
            name='rsi_bracket',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventsrsi',
            name='rsi_event_type',
            field=models.CharField(default='brackets', max_length=8),
        ),
    ]
