# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_annpriceclassification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annpriceclassification',
            old_name='nn_model',
            new_name='ann_model',
        ),
    ]
