# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_auto_20180110_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsrsi',
            name='rsi_event_type',
            field=models.CharField(default='brackets', max_length=10),
        ),
    ]
