# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_auto_20180330_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceResampled',
        ),
    ]
