# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0015_auto_20180111_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsElementary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('counter_currency', models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')], default=0)),
                ('transaction_currency', models.CharField(max_length=6)),
                ('resample_period', models.PositiveSmallIntegerField(default=15)),
                ('event_name', models.CharField(default='none', max_length=32)),
                ('event_value', models.IntegerField(null=True)),
                ('event_second_value', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EventsElementory',
        ),
    ]
