# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0016_add_more_sources'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['timestamp', 'source', 'transaction_currency', 'counter_currency'], name='indicator_p_timesta_29a5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='priceresampl',
            index=models.Index(fields=['timestamp', 'source', 'resample_period', 'transaction_currency', 'counter_currency'], name='indicator_p_timesta_8a5895_idx'),
        ),
        migrations.AddIndex(
            model_name='sma',
            index=models.Index(fields=['source', 'resample_period', 'transaction_currency', 'counter_currency', 'sma_period'], name='indicator_s_source_e6d568_idx'),
        ),
    ]
