# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0016_auto_20180111_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sma',
            name='sma_midpoint_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
