# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0017_add_indexes_to_price_sma_priceresampl'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventselementary',
            index=models.Index(fields=['transaction_currency', 'source', 'counter_currency', 'resample_period', 'event_name', 'timestamp'], name='indicator_e_transac_b99fce_idx'),
        ),
        migrations.AddIndex(
            model_name='rsi',
            index=models.Index(fields=['transaction_currency', 'counter_currency', 'source', 'resample_period'], name='indicator_r_transac_c5b0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='volume',
            index=models.Index(fields=['transaction_currency', 'counter_currency', 'source', 'timestamp'], name='indicator_v_transac_e2dbb6_idx'),
        ),
    ]
