# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0017_sma_sma_midpoint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sma',
            name='sma_high_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
