# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0018_auto_20180608_1150'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='priceresampl',
            name='indicator_p_source_61ed12_idx',
        ),
        migrations.AddIndex(
            model_name='priceresampl',
            index=models.Index(fields=['transaction_currency', 'counter_currency', 'source', 'resample_period'], name='indicator_p_transac_edf618_idx'),
        ),
    ]
