# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0019_auto_20180614_1013'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='priceresampl',
            name='indicator_p_transac_edf618_idx',
        ),
        migrations.AddIndex(
            model_name='priceresampl',
            index=models.Index(fields=['transaction_currency', 'counter_currency', 'source', 'resample_period', 'timestamp'], name='indicator_p_transac_266f85_idx'),
        ),
    ]
