# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0020_auto_20180615_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex'), (2, 'binance'), (3, 'bitfinex'), (4, 'kucoin'), (5, 'gdax'), (6, 'hitbtc')])),
                ('transaction_currency', models.CharField(max_length=6)),
                ('counter_currency', models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')])),
                ('open_p', models.BigIntegerField(null=True)),
                ('high', models.BigIntegerField(null=True)),
                ('low', models.BigIntegerField(null=True)),
                ('close', models.BigIntegerField(null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
