# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0020_auto_20180615_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='annpriceclassification',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventselementary',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventslogical',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='priceresampl',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rsi',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sma',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='new_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
