# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 10:31
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime


def myCustomFunction(apps, schema_editor):

    models = []
    models.append(apps.get_model('ai', 'annmodel'))
    models.append(apps.get_model('backtesting', 'backtest'))
    models.append(apps.get_model('channel', 'exchangedata'))
    models.append(apps.get_model('signal', 'signal'))
    for model_name in ['annpriceclassification', 'eventselementary', 'eventslogical', 'price', 'priceresampl', 'rsi', 'sma', 'volume']:
        models.append(apps.get_model('indicator', model_name))

    for model in models:
        for instance in model.objects.all():
            instance.new_timestamp = instance.utcfromtimestamp(model.timestamp)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0021_auto_20180616_1028'),
        ('channel', '0003_exchangedata_new_timestamp'),
        ('backtesting', '0004_backtest_new_timestamp'),
        ('ai', '0004_annmodel_new_timestamp'),
        ('signal', '0012_signal_new_timestamp'),
    ]

    operations = [
        migrations.RunPython(myCustomFunction, reverse_code=migrations.RunPython.noop)
    ]
