# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0021_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
