# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0024_add_index_to_pricehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set([('timestamp', 'transaction_currency', 'counter_currency', 'source')]),
        ),
    ]
