# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0025_add_unique_together_to_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='annpriceclassification',
            name='ai_model',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
