# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0026_annpriceclassification_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceresampl',
            name='volume_variance',
            field=models.FloatField(null=True),
        ),
    ]
