# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex')])),
                ('model_name', models.CharField(max_length=32)),
                ('s3_file', models.TextField()),
                ('period', models.PositiveSmallIntegerField()),
                ('slide_win_size', models.SmallIntegerField()),
                ('predicted_win_size', models.SmallIntegerField()),
                ('delta_tolerance', models.FloatField()),
                ('train_accuracy', models.FloatField(null=True)),
                ('train_f1_score', models.FloatField(null=True)),
                ('validation_accuracy', models.FloatField(null=True)),
                ('validation_f1_score', models.FloatField(null=True)),
                ('train_data_description', models.TextField(blank=True, null=True)),
                ('features_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
