# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annmodel',
            old_name='s3_file',
            new_name='s3_model_file',
        ),
        migrations.AddField(
            model_name='annmodel',
            name='s3_notebook_file',
            field=models.TextField(null=True),
        ),
    ]
