# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('generated', models.CharField(max_length=16)),
                ('last_backtested_performance', models.FloatField(null=True)),
                ('implementation_class_name', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
