# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_auto_20180416_1542'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('implementation_class_name', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('generated', models.CharField(max_length=16)),
                ('last_backtested_performance', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
