# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20180416_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyref',
            name='implementation_module_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
