# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategyref_implementation_module_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrategyRef',
        ),
    ]
